version: "2"
services:
        jup:
                image: jupyter/scipy-notebook
                volumes:
                        - .:/home/jovyan/work
                ports:
                        - 8888:8888
