////////////////////////////////////////////////////////////////////////////////
// Copyright (c) 1995-2008 Xilinx, Inc.  All rights reserved.
////////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   / 
// /___/  \  /    Vendor: Xilinx 
// \   \   \/     Version : 10.1.03
//  \   \         Application : xaw2verilog
//  /   /         Filename : clockgen.v
// /___/   /\     Timestamp : 02/07/2012 20:24:09
// \   \  /  \ 
//  \___\/\___\ 
//
//Command: xaw2verilog -intstyle /home/seva/src/vp2/rtl/vp2/clockgen.xaw -st clockgen.v
//Design Name: clockgen
//Device: xc2vp50-6ff1152
//
// Module clockgen
// Generated by Xilinx Architecture Wizard
// Written for synthesis tool: XST
`timescale 1ns / 1ps

module clockgen(CLKIN_IN, 
                USER_RST_IN, 
                CLKDV_OUT, 
                CLKIN_IBUFG_OUT, 
                CLK0_OUT, 
                LOCKED_OUT);

    input CLKIN_IN;
    input USER_RST_IN;
   output CLKDV_OUT;
   output CLKIN_IBUFG_OUT;
   output CLK0_OUT;
   output LOCKED_OUT;
   
   wire CLKDV_BUF;
   wire CLKFB_IN;
   wire CLKIN_IBUFG;
   wire CLK0_BUF;
   wire FDS_Q_OUT;
   wire FD1_Q_OUT;
   wire FD2_Q_OUT;
   wire FD3_Q_OUT;
   wire GND_BIT;
   wire OR3_O_OUT;
   wire RST_IN;
   
   assign GND_BIT = 0;
   assign CLKIN_IBUFG_OUT = CLKIN_IBUFG;
   assign CLK0_OUT = CLKFB_IN;
   BUFG CLKDV_BUFG_INST (.I(CLKDV_BUF), 
                         .O(CLKDV_OUT));
   IBUFG CLKIN_IBUFG_INST (.I(CLKIN_IN), 
                           .O(CLKIN_IBUFG));
   BUFG CLK0_BUFG_INST (.I(CLK0_BUF), 
                        .O(CLKFB_IN));
   DCM DCM_INST (.CLKFB(CLKFB_IN), 
                 .CLKIN(CLKIN_IBUFG), 
                 .DSSEN(GND_BIT), 
                 .PSCLK(GND_BIT), 
                 .PSEN(GND_BIT), 
                 .PSINCDEC(GND_BIT), 
                 .RST(RST_IN), 
                 .CLKDV(CLKDV_BUF), 
                 .CLKFX(), 
                 .CLKFX180(), 
                 .CLK0(CLK0_BUF), 
                 .CLK2X(), 
                 .CLK2X180(), 
                 .CLK90(), 
                 .CLK180(), 
                 .CLK270(), 
                 .LOCKED(LOCKED_OUT), 
                 .PSDONE(), 
                 .STATUS());
   defparam DCM_INST.CLK_FEEDBACK = "1X";
   defparam DCM_INST.CLKDV_DIVIDE = 2.0;
   defparam DCM_INST.CLKFX_DIVIDE = 1;
   defparam DCM_INST.CLKFX_MULTIPLY = 4;
   defparam DCM_INST.CLKIN_DIVIDE_BY_2 = "FALSE";
   defparam DCM_INST.CLKIN_PERIOD = 10.000;
   defparam DCM_INST.CLKOUT_PHASE_SHIFT = "NONE";
   defparam DCM_INST.DESKEW_ADJUST = "SYSTEM_SYNCHRONOUS";
   defparam DCM_INST.DFS_FREQUENCY_MODE = "LOW";
   defparam DCM_INST.DLL_FREQUENCY_MODE = "LOW";
   defparam DCM_INST.DUTY_CYCLE_CORRECTION = "TRUE";
   defparam DCM_INST.FACTORY_JF = 16'hC080;
   defparam DCM_INST.PHASE_SHIFT = 0;
   defparam DCM_INST.STARTUP_WAIT = "FALSE";
   FDS FDS_INST (.C(CLKIN_IBUFG), 
                 .D(GND_BIT), 
                 .S(GND_BIT), 
                 .Q(FDS_Q_OUT));
   FD FD1_INST (.C(CLKIN_IBUFG), 
                .D(FDS_Q_OUT), 
                .Q(FD1_Q_OUT));
   FD FD2_INST (.C(CLKIN_IBUFG), 
                .D(FD1_Q_OUT), 
                .Q(FD2_Q_OUT));
   FD FD3_INST (.C(CLKIN_IBUFG), 
                .D(FD2_Q_OUT), 
                .Q(FD3_Q_OUT));
   OR2 OR2_INST (.I0(USER_RST_IN), 
                 .I1(OR3_O_OUT), 
                 .O(RST_IN));
   OR3 OR3_INST (.I0(FD3_Q_OUT), 
                 .I1(FD2_Q_OUT), 
                 .I2(FD1_Q_OUT), 
                 .O(OR3_O_OUT));
endmodule
